import { LogoSettings } from ".";

const additionalPresets: LogoSettings[] = [
  {
    background: "linear-gradient(to left top, rgb(64, 224, 208), rgb(255, 140, 0), rgb(255, 0, 128))",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "FlaskConical",
    borderRadius: 0.1,
    rotation: 0,
    size: 0.8,
  },
  {
    background: "linear-gradient(to bottom right, #FF0080, #7928CA)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Zap",
    borderRadius: 0.5,
    rotation: 0,
    size: 0.8,
  },
  {
    background: "linear-gradient(to right, #4158D0, #C850C0, #FFCC70)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 0.9,
    strokeWidth: 2.2,
    iconName: "Palette",
    borderRadius: 0.1,
    rotation: 15,
    size: 0.8,
  },
  {
    background: "linear-gradient(to top right, #4158D0 0%, #C850C0 46%, #FFCC70 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Paintbrush",
    borderRadius: 0.4,
    rotation: 0,
    size: 0.75,
  },
  {
    background: "linear-gradient(to bottom right, #0093E9 0%, #80D0C7 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.3,
    iconName: "Droplets",
    borderRadius: 0.1,
    rotation: 0,
    size: 0.8,
  },
  {
    background: "linear-gradient(to bottom right, #8EC5FC 0%, #E0C3FC 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.8,
    strokeWidth: 2,
    iconName: "Cloud",
    borderRadius: 1,
    rotation: 0,
    size: 0.75,
  },
  {
    background: "linear-gradient(to top right, #85FFBD 0%, #FFFB7D 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.9,
    strokeWidth: 2.1,
    iconName: "Leaf",
    borderRadius: 0.25,
    rotation: 45,
    size: 0.8
  },
  {
    background: "linear-gradient(to right, #FF9A8B, #FF6A88, #FF99AC)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Heart",
    borderRadius: 0.35,
    rotation: 0,
    size: 0.8,
  },
  {
    background: "linear-gradient(to top right, #FBDA61 0%, #FF5ACD 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.2,
    iconName: "Sun",
    borderRadius: 1,
    rotation: 15,
    size: 0.75,
  },
  {
    background: "linear-gradient(to bottom right, #84FAB0 0%, #8FD3F4 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.9,
    strokeWidth: 2,
    iconName: "Waves",
    borderRadius: 0.7,
    rotation: 0,
    size: 0.8,
  },
  {
    background: "linear-gradient(to right, #FA8BFF, #2BD2FF, #2BFF88)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.2,
    iconName: "Sparkles",
    borderRadius: 0.35,
    rotation: 30,
    size: 0.75,
  },
  {
    background: "linear-gradient(to right, #FF3CAC, #784BA0, #2B86C5)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.1,
    iconName: "Star",
    borderRadius: 0.4,
    rotation: 15,
    size: 0.8,
  },
  {
    background: "linear-gradient(to top right, #FA8BFF 0%, #2BD2FF 50%, #2BFF88 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.9,
    strokeWidth: 2,
    iconName: "Rocket",
    borderRadius: 0.25,
    rotation: 45,
    size: 0.75,
  },
  {
    background: "linear-gradient(to bottom right, #0093E9 0%, #80D0C7 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.3,
    iconName: "Globe",
    borderRadius: 1,
    rotation: 0,
    size: 0.8,
  },
  {
    background: "linear-gradient(to right, #FF9A8B, #FF6A88, #FF99AC)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Music",
    borderRadius: 0.35,
    rotation: -15,
    size: 0.75,
  },
  {
    background: "linear-gradient(to top right, #85FFBD 0%, #FFFB7D 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.8,
    strokeWidth: 2.2,
    iconName: "TreePine",
    borderRadius: 0.3,
    rotation: 0,
    size: 0.8,
  },
  {
    background: "linear-gradient(to bottom right, #FBAB7E 0%, #F7CE68 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.1,
    iconName: "Flame",
    borderRadius: 0.4,
    rotation: 15,
    size: 0.75,
  },
  {
    background: "linear-gradient(to top right, #FA8BFF 0%, #2BD2FF 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 0.9,
    strokeWidth: 2,
    iconName: "Infinity",
    borderRadius: 0.35,
    rotation: 0,
    size: 0.8,
  }
];

export default additionalPresets;