import { LogoSettings } from ".";

const additionalPresets: LogoSettings[] = [
  // Existing presets...
  {
    background: "linear-gradient(to left top, rgb(64, 224, 208), rgb(255, 140, 0), rgb(255, 0, 128))",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "FlaskConical",
    radius: 80,
    rotation: 0,
    size: 400,
  },
  {
    background: "linear-gradient(to bottom right, #FF0080, #7928CA)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Zap",
    radius: 50,
    rotation: 0,
    size: 400,
  },
  // New gradients from gradient.page
  {
    background: "linear-gradient(to right, #4158D0, #C850C0, #FFCC70)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 0.9,
    strokeWidth: 2.2,
    iconName: "Palette",
    radius: 85,
    rotation: 15,
    size: 400,
  },
  {
    background: "linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Paintbrush",
    radius: 40,
    rotation: 0,
    size: 380,
  },
  {
    background: "linear-gradient(160deg, #0093E9 0%, #80D0C7 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.3,
    iconName: "Droplets",
    radius: 200,
    rotation: 0,
    size: 400,
  },
  {
    background: "linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.8,
    strokeWidth: 2,
    iconName: "Cloud",
    radius: 45,
    rotation: 0,
    size: 390,
  },
  {
    background: "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.9,
    strokeWidth: 2.1,
    iconName: "Leaf",
    radius: 25,
    rotation: 45,
    size: 410,
  },
  {
    background: "linear-gradient(to right, #FF9A8B, #FF6A88, #FF99AC)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Heart",
    radius: 35,
    rotation: 0,
    size: 400,
  },
  {
    background: "linear-gradient(45deg, #FBDA61 0%, #FF5ACD 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.2,
    iconName: "Sun",
    radius: 250,
    rotation: 15,
    size: 380,
  },
  {
    background: "linear-gradient(120deg, #84FAB0 0%, #8FD3F4 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.9,
    strokeWidth: 2,
    iconName: "Waves",
    radius: 70,
    rotation: 0,
    size: 400,
  },
  {
    background: "linear-gradient(to right, #FA8BFF, #2BD2FF, #2BFF88)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.2,
    iconName: "Sparkles",
    radius: 35,
    rotation: 30,
    size: 390,
  },
  {
    background: "linear-gradient(to right, #FF3CAC, #784BA0, #2B86C5)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.1,
    iconName: "Star",
    radius: 40,
    rotation: 15,
    size: 400,
  },
  {
    background: "linear-gradient(45deg, #FA8BFF 0%, #2BD2FF 50%, #2BFF88 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.9,
    strokeWidth: 2,
    iconName: "Rocket",
    radius: 25,
    rotation: 45,
    size: 380,
  },
  {
    background: "linear-gradient(160deg, #0093E9 0%, #80D0C7 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.3,
    iconName: "Globe",
    radius: 250,
    rotation: 0,
    size: 400,
  },
  {
    background: "linear-gradient(to right, #FF9A8B, #FF6A88, #FF99AC)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2,
    iconName: "Music",
    radius: 35,
    rotation: -15,
    size: 390,
  },
  {
    background: "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%)",
    fillColor: "#000000",
    fillOpacity: 0.1,
    strokeColor: "#000000",
    strokeOpacity: 0.8,
    strokeWidth: 2.2,
    iconName: "TreePine",
    radius: 30,
    rotation: 0,
    size: 400,
  },
  {
    background: "linear-gradient(62deg, #FBAB7E 0%, #F7CE68 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0.1,
    strokeColor: "#ffffff",
    strokeOpacity: 1,
    strokeWidth: 2.1,
    iconName: "Flame",
    radius: 40,
    rotation: 15,
    size: 380,
  },
  {
    background: "linear-gradient(45deg, #FA8BFF 0%, #2BD2FF 100%)",
    fillColor: "#ffffff",
    fillOpacity: 0,
    strokeColor: "#ffffff",
    strokeOpacity: 0.9,
    strokeWidth: 2,
    iconName: "Infinity",
    radius: 35,
    rotation: 0,
    size: 400,
  }
];

export default additionalPresets;